spring.application.name=springBootDemo
server.port=9099
# sql connectivity
spring.datasource.url=jdbc:mysql://localhost:3306/dbDepartment
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=gnani@123
spring.jpa.hibernate.ddl-auto=update
welcome.message="welocome Buddy"
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=env,beans

